surveil:
  build: .

shinken:
  build: tools/docker/shinken_container/

mongo:
  image: mongo

influxdb:
  image: savoirfairelinux/influxdb

grafana:
  image: savoirfairelinux/grafana
  environment:
    INFLUXDB_HOST: "influxdb"
    INFLUXDB_PORT: "8086"
    INFLUXDB_NAME: "db"
    INFLUXDB_USER: "root"
    INFLUXDB_PASS: "root"

bansho:
  image: savoirfairelinux/bansho
  environment:
    BANSHO_BACKEND: "surveil"
    BANSHO_SURVEIL_URL: "http://surveil:8080/"
