surveil:
  extends:
    file: docker-compose-common.yml
    service: surveil
  links:
   - mongo
   - influxdb
   - shinken
  ports:
   - "8080:8080"
  environment:
    PBR_VERSION: "PROD"

shinken:
  extends:
    file: docker-compose-common.yml
    service: shinken
  links:
    - mongo
    - influxdb
  ports:
    - "7767:7767"

mongo:
  extends:
    file: docker-compose-common.yml
    service: mongo
  ports:
   - "27017:27017"
  command:
      "mongod --smallfiles"
  volumes:
   - ./container-data/mongodb:/data/db

influxdb:
  extends:
    file: docker-compose-common.yml
    service: influxdb
  environment:
    PRE_CREATE_DB: "db"
  ports:
    - "8083:8083"
    - "8086:8086"
  volumes:
   - ./container-data/influxdb:/data

grafana:
  extends:
    file: docker-compose-common.yml
    service: grafana
  ports:
    - "80:80"
  links:
    - influxdb

bansho:
  extends:
    file: docker-compose-common.yml
    service: bansho
  ports:
    - "8888:8888"
  links:
    - surveil
